-- Migration 0011: Seed initial courses into D1

INSERT OR IGNORE INTO courses (id, slug, title, description, estimated_time, course_type, lifecycle_state, difficulty, capability_tags, last_updated, href, sections, tools_used, release_date, "order")
VALUES
(
  'ai-foundations',
  'ai-foundations',
  'AI Foundations',
  'A comprehensive introduction to AI concepts and tools for beginners.',
  '1 hour',
  'deep',
  'current',
  NULL,
  '["Fundamentals","Concepts","Getting Started"]',
  'January 25, 2026',
  '/learn/courses/ai-foundations',
  '[{"id":"intro","title":"Introduction","anchor":"intro"},{"id":"what-is-ai","title":"What is AI?","anchor":"what-is-ai"},{"id":"how-llms-work","title":"How LLMs Work","anchor":"how-llms-work"},{"id":"practical-uses","title":"Practical Uses","anchor":"practical-uses"}]',
  '["chatgpt","claude"]',
  NULL,
  0
),
(
  'mastering-chatgpt',
  'mastering-chatgpt',
  'Mastering AI Prompts: Professional Skills for Real-World Results',
  'Why most prompts produce average results — and the professional techniques that fix it.',
  '90 min',
  'deep',
  'current',
  NULL,
  '["ChatGPT","Prompting","Productivity"]',
  'January 20, 2026',
  '/learn/courses/mastering-chatgpt',
  '[]',
  '["chatgpt"]',
  NULL,
  1
),
(
  'ai-email',
  'ai-email',
  'AI for Email & Communication',
  'Practical course on using AI to write better emails, messages, and professional communications.',
  '45 min',
  'short',
  'current',
  NULL,
  '["Email","Writing","Communication"]',
  'January 15, 2026',
  '/learn/courses/ai-email',
  '[]',
  '["chatgpt","claude"]',
  NULL,
  2
),
(
  'ai-safety',
  'ai-safety',
  'Understanding AI Safety & Ethics',
  'What you need to know about using AI responsibly and safely in personal and professional contexts.',
  '30 min',
  'reference',
  'current',
  NULL,
  '["Safety","Ethics","Privacy"]',
  'January 10, 2026',
  '/learn/courses/ai-safety',
  '[]',
  '[]',
  NULL,
  3
),
(
  'prompt-engineering-basics',
  'prompt-engineering-basics',
  'Prompt Engineering Basics',
  'Learn the fundamentals of writing effective prompts that get better AI responses.',
  '60 min',
  'short',
  'reference',
  NULL,
  '["Prompting","Fundamentals"]',
  'December 15, 2025',
  '/learn/courses/prompt-engineering-basics',
  '[]',
  '[]',
  NULL,
  4
),
(
  'gpt-3-to-4-migration',
  'gpt-3-to-4-migration',
  'GPT-3 to GPT-4 Migration Guide',
  'Historical reference for users transitioning from GPT-3 to GPT-4 capabilities.',
  '20 min',
  'reference',
  'legacy',
  NULL,
  '["ChatGPT","Migration"]',
  'March 1, 2024',
  '/learn/courses/gpt-3-to-4-migration',
  '[]',
  '[]',
  NULL,
  5
);
